version: "3.8"
services:
  docker:
    image: docker:dind
    privileged: true
    networks: 
      - jenkins
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes: 
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
      - $HOME:/home
  jenkins:
    image: jenkinsci/blueocean
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - JENKINS_OPTS="--httpPort=${JENKINS_PORT}"
    volumes: 
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - $HOME:/home
    ports:
        - "${JENKINS_PORT}:${JENKINS_PORT}"
  socketxp:
    env_file: 
      - .env
    build: 
      context: ./socketxp
      dockerfile: Dockerfile
      args: 
        - AUTH_TOKEN=${TOKEN}
        - JENKINS=${JENKINS_HOST}
        - PORT=${JENKINS_PORT}

volumes:
  jenkins-docker-certs:
  jenkins-data:
  socketxp-data:

networks:
  jenkins:
